# Generated by Django 5.2 on 2025-05-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_fileupload_yt_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='yt_video_link',
            new_name='yt_video_id',
        ),
    ]
